// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiKdZYAB57B0ijtUlsMWn3Ha4B0lNKkNk',
    appId: '1:463363516211:web:9acc1a3fecff3e6fb7c046',
    messagingSenderId: '463363516211',
    projectId: 'chat-app-e77ea',
    authDomain: 'chat-app-e77ea.firebaseapp.com',
    storageBucket: 'chat-app-e77ea.firebasestorage.app',
    measurementId: 'G-B4JC25PPV2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAXuqkOVIhTCroVKBbgDZJbR2-ESpz6yI',
    appId: '1:463363516211:android:c53679795c247803b7c046',
    messagingSenderId: '463363516211',
    projectId: 'chat-app-e77ea',
    storageBucket: 'chat-app-e77ea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOOQqHsuEQflLZwmqu073CQ3zy4G6ajlg',
    appId: '1:463363516211:ios:194d837b0012f820b7c046',
    messagingSenderId: '463363516211',
    projectId: 'chat-app-e77ea',
    storageBucket: 'chat-app-e77ea.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOOQqHsuEQflLZwmqu073CQ3zy4G6ajlg',
    appId: '1:463363516211:ios:194d837b0012f820b7c046',
    messagingSenderId: '463363516211',
    projectId: 'chat-app-e77ea',
    storageBucket: 'chat-app-e77ea.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiKdZYAB57B0ijtUlsMWn3Ha4B0lNKkNk',
    appId: '1:463363516211:web:d4315cfa4e9aa84ab7c046',
    messagingSenderId: '463363516211',
    projectId: 'chat-app-e77ea',
    authDomain: 'chat-app-e77ea.firebaseapp.com',
    storageBucket: 'chat-app-e77ea.firebasestorage.app',
    measurementId: 'G-3PHK182M0F',
  );
}
